### ISSUE TITLE
Tests in backend & frontend

### ISSUE THREAD

**Issue by Jblew** [wise-team/wise-hub#24]
- [ ] - Backend/lib and Bacnend/common
  - [ ] - hartbeat
    - [ ] - Refactor to meet SOLID(at the first moment SRP and OCP) principles
    - [ ] - Write unit tests
  - [ ] - to be continued

- [ ] - Backend/api
  - [ ] - to be specified

- [ ] - Backend/daemon
  - [ ] - to be specified

- [ ] - Backend/publisher
  - [ ] - to be specified

- [ ] - Backend/realtime
  - [ ] - to be specified

- [ ] - Frontend
  - [ ] - to be specified

- [ ] - Monitoring
  - [ ] - to be specified

**Comment by noisy** [comment]
@Jblew please make a list of modules or classes which needed better unit test coverage
